EsAdminActions = {
    tabs = {
        { id = 'all', label = 'All' },
        { id = 'player', label = 'Player' },
        { id = 'vehicle', label = 'Vehicle' },
        { id = 'world', label = 'World' },
        { id = 'weapons', label = 'Weapons' },
        { id = 'teleport', label = 'Teleport' },
        { id = 'appearance', label = 'Appearance' },
        { id = 'vehicle_custom', label = 'Customizer' },
        { id = 'inventory', label = 'Inventory', framework = 'qbx' },
        { id = 'garage', label = 'Garage', framework = 'qbx' },
        { id = 'dev', label = 'Dev' },
        { id = 'recording', label = 'Recording' },
        { id = 'options', label = 'Options' },
        { id = 'server', label = 'Server' },
        { id = 'favorites', label = 'Favorites' },
    },
    actions = {
        {
            id = 'player.godmode',
            label = 'God Mode',
            description = 'Prevent death and damage',
            tab = 'player',
            type = 'toggle',
        },
        {
            id = 'player.invisible',
            label = 'Invisibility',
            description = 'Toggle player visibility',
            tab = 'player',
            type = 'toggle',
        },
        {
            id = 'player.noclip',
            label = 'Noclip',
            description = 'Move freely through the world',
            tab = 'player',
            type = 'toggle',
        },
        {
            id = 'player.superjump',
            label = 'Super Jump',
            description = 'Jump higher than normal',
            tab = 'player',
            type = 'toggle',
        },
        {
            id = 'player.infiniteStamina',
            label = 'Infinite Stamina',
            description = 'Never run out of stamina',
            tab = 'player',
            type = 'toggle',
        },
        {
            id = 'player.noRagdoll',
            label = 'No Ragdoll',
            description = 'Disable ragdoll effects',
            tab = 'player',
            type = 'toggle',
        },
        {
            id = 'player.fastRun',
            label = 'Fast Run',
            description = 'Increase run speed',
            tab = 'player',
            type = 'toggle',
        },
        {
            id = 'player.fastSwim',
            label = 'Fast Swim',
            description = 'Increase swim speed',
            tab = 'player',
            type = 'toggle',
        },
        {
            id = 'player.heal',
            label = 'Heal',
            description = 'Restore full health',
            tab = 'player',
            type = 'action',
        },
        {
            id = 'player.armor',
            label = 'Max Armor',
            description = 'Set armor to maximum',
            tab = 'player',
            type = 'action',
        },
        {
            id = 'player.revive',
            label = 'Revive',
            description = 'Revive and restore health',
            tab = 'player',
            type = 'action',
        },
        {
            id = 'player.clearWanted',
            label = 'Clear Wanted',
            description = 'Remove wanted level',
            tab = 'player',
            type = 'action',
        },
        {
            id = 'player.neverWanted',
            label = 'Never Wanted',
            description = 'Prevent police attention',
            tab = 'player',
            type = 'toggle',
        },
        {
            id = 'player.setWantedLevel',
            label = 'Set Wanted Level',
            description = 'Set your wanted level (0-5)',
            tab = 'player',
            type = 'select',
            values = {
                { label = '0 Stars', value = 0 },
                { label = '1 Star', value = 1 },
                { label = '2 Stars', value = 2 },
                { label = '3 Stars', value = 3 },
                { label = '4 Stars', value = 4 },
                { label = '5 Stars', value = 5 },
            },
        },
        {
            id = 'player.freeze',
            label = 'Freeze Player',
            description = 'Lock player in place',
            tab = 'player',
            type = 'toggle',
        },
        {
            id = 'player.everyoneIgnores',
            label = 'Everyone Ignores',
            description = 'NPCs and police ignore you',
            tab = 'player',
            type = 'toggle',
        },
        {
            id = 'player.cleanPlayer',
            label = 'Clean Player',
            description = 'Remove dirt and blood',
            tab = 'player',
            type = 'action',
        },
        {
            id = 'player.dryPlayer',
            label = 'Dry Player',
            description = 'Remove wetness',
            tab = 'player',
            type = 'action',
        },
        {
            id = 'player.wetPlayer',
            label = 'Wet Player',
            description = 'Make player wet',
            tab = 'player',
            type = 'action',
        },
        {
            id = 'player.setModel',
            label = 'Set Ped Model',
            description = 'Change player model',
            tab = 'player',
            type = 'prompt',
            prompt = {
                title = 'Set Ped Model',
                fields = {
                    { name = 'model', label = 'Model', placeholder = 'mp_m_freemode_01' },
                },
            },
        },
        {
            id = 'player.saveMpPed',
            label = 'Save MP Ped',
            description = 'Save current freemode appearance',
            tab = 'player',
            type = 'prompt',
            prompt = {
                title = 'Save MP Ped',
                fields = {
                    { name = 'name', label = 'Name', placeholder = 'MyFreemode' },
                },
            },
        },
        {
            id = 'player.loadMpPed',
            label = 'Load MP Ped',
            description = 'Load a saved MP ped by name',
            tab = 'player',
            type = 'prompt',
            prompt = {
                title = 'Load MP Ped',
                fields = {
                    { name = 'name', label = 'Name', placeholder = 'MyFreemode' },
                },
            },
        },
        {
            id = 'player.setDefaultSavedPed',
            label = 'Set Default Outfit',
            description = 'Use a saved MP ped as the default restore outfit',
            tab = 'appearance',
            type = 'prompt',
            prompt = {
                title = 'Set Default Outfit',
                fields = {
                    { name = 'name', label = 'Saved outfit name', placeholder = 'MyFreemode' },
                },
            },
        },
        {
            id = 'player.randomizeMpFace',
            label = 'Randomize MP Face',
            description = 'Randomize freemode heritage, face sliders, and overlays',
            tab = 'appearance',
            type = 'action',
        },
        {
            id = 'player.clearPedTattoos',
            label = 'Clear Ped Tattoos',
            description = 'Clear all current ped decorations and tattoos',
            tab = 'appearance',
            type = 'action',
        },
        {
            id = 'player.savePed',
            label = 'Save Ped',
            description = 'Save current ped model',
            tab = 'player',
            type = 'prompt',
            prompt = {
                title = 'Save Ped',
                fields = {
                    { name = 'name', label = 'Name', placeholder = 'MyPed' },
                },
            },
        },
        {
            id = 'player.loadPed',
            label = 'Load Ped',
            description = 'Load a saved ped by name',
            tab = 'player',
            type = 'prompt',
            prompt = {
                title = 'Load Ped',
                fields = {
                    { name = 'name', label = 'Name', placeholder = 'MyPed' },
                },
            },
        },
        {
            id = 'player.copyCoords',
            label = 'Copy Coords',
            description = 'Copy current coords to clipboard',
            tab = 'player',
            type = 'action',
        },
        {
            id = 'player.copyHeading',
            label = 'Copy Heading',
            description = 'Copy heading to clipboard',
            tab = 'player',
            type = 'action',
        },

        -- ================================================================
        -- QBX PLAYER MANAGEMENT (target other players)
        -- These actions operate on a selected target player from the player list
        -- ================================================================
        {
            id = 'player.kill',
            label = 'Kill Player',
            description = 'Kill a target player',
            tab = 'player',
            type = 'action',
            framework = 'qbx',
        },
        {
            id = 'player.reviveTarget',
            label = 'Revive Player',
            description = 'Revive a target player (requires qbx_medical or ambulancejob)',
            tab = 'player',
            type = 'action',
            framework = 'qbx',
        },
        {
            id = 'player.sitInVehicle',
            label = 'Sit In Vehicle',
            description = 'Teleport into a target player\'s vehicle',
            tab = 'player',
            type = 'action',
            framework = 'qbx',
        },
        {
            id = 'player.setJob',
            label = 'Set Job',
            description = 'Set a target player\'s job and grade',
            tab = 'player',
            type = 'action',
            framework = 'qbx',
        },
        {
            id = 'player.setGang',
            label = 'Set Gang',
            description = 'Set a target player\'s gang and grade',
            tab = 'player',
            type = 'action',
            framework = 'qbx',
        },
        {
            id = 'player.setCash',
            label = 'Set Cash',
            description = 'Set a target player\'s cash amount',
            tab = 'player',
            type = 'action',
            framework = 'qbx',
        },
        {
            id = 'player.setBank',
            label = 'Set Bank',
            description = 'Set a target player\'s bank balance',
            tab = 'player',
            type = 'action',
            framework = 'qbx',
        },
        {
            id = 'player.giveMoney',
            label = 'Give Money',
            description = 'Give cash or bank money to a target player',
            tab = 'player',
            type = 'action',
            framework = 'qbx',
        },
        {
            id = 'player.setFood',
            label = 'Set Hunger',
            description = 'Set a target player\'s hunger level (0-100)',
            tab = 'player',
            type = 'action',
            framework = 'qbx',
        },
        {
            id = 'player.setThirst',
            label = 'Set Thirst',
            description = 'Set a target player\'s thirst level (0-100)',
            tab = 'player',
            type = 'action',
            framework = 'qbx',
        },
        {
            id = 'player.setStress',
            label = 'Set Stress',
            description = 'Set a target player\'s stress level (0-100)',
            tab = 'player',
            type = 'action',
            framework = 'qbx',
        },
        {
            id = 'player.openInventory',
            label = 'Open Inventory',
            description = 'Open a target player\'s inventory',
            tab = 'player',
            type = 'action',
            framework = 'qbx',
        },
        {
            id = 'player.setRoutingBucket',
            label = 'Set Routing Bucket',
            description = 'Move a target player to a different routing bucket',
            tab = 'player',
            type = 'action',
            framework = 'qbx',
        },

        -- ================================================================
        -- VEHICLES
        -- ================================================================
        {
            id = 'vehicle.spawn',
            label = 'Spawn Vehicle',
            description = 'Preview and spawn a vehicle by model name',
            tab = 'vehicle',
            type = 'action',
        },
        {
            id = 'vehicle.preview',
            label = 'Vehicle Preview',
            description = 'Preview in world, toggle extras, spawn with current setup',
            tab = 'vehicle',
            type = 'action',
        },
        {
            id = 'vehicle.personal',
            label = 'Personal Vehicles',
            description = 'Manage your saved vehicles',
            tab = 'vehicle',
            type = 'action',
        },
        {
            id = 'vehicle.savePersonal',
            label = 'Save Current Vehicle',
            description = 'Save current vehicle to your personal list',
            tab = 'vehicle',
            type = 'prompt',
            prompt = {
                title = 'Save to Personal Vehicles',
                fields = {
                    { name = 'name', label = 'Name', placeholder = 'MyCar' },
                },
            },
        },
        {
            id = 'vehicle.repair',
            label = 'Repair Vehicle',
            description = 'Fix and restore current vehicle',
            tab = 'vehicle',
            type = 'action',
        },
        {
            id = 'vehicle.clean',
            label = 'Clean Vehicle',
            description = 'Wash current vehicle',
            tab = 'vehicle',
            type = 'action',
        },
        {
            id = 'vehicle.delete',
            label = 'Delete Vehicle',
            description = 'Delete current vehicle',
            tab = 'vehicle',
            type = 'action',
            requiresConfirm = true,
        },
        {
            id = 'vehicle.destroyEngine',
            label = 'Destroy Engine',
            description = 'Disable the current vehicle engine',
            tab = 'vehicle',
            type = 'action',
            requiresConfirm = true,
        },
        {
            id = 'vehicle.flip',
            label = 'Flip Vehicle',
            description = 'Flip and align vehicle',
            tab = 'vehicle',
            type = 'action',
        },
        {
            id = 'vehicle.engine',
            label = 'Engine Toggle',
            description = 'Toggle engine state',
            tab = 'vehicle',
            type = 'toggle',
        },
        {
            id = 'vehicle.invincible',
            label = 'Vehicle Godmode',
            description = 'Prevent vehicle damage',
            tab = 'vehicle',
            type = 'toggle',
        },
        {
            id = 'vehicle.keepClean',
            label = 'Keep Vehicle Clean',
            description = 'Vehicle stays clean automatically',
            tab = 'vehicle',
            type = 'toggle',
        },
        {
            id = 'vehicle.speedLimiter',
            label = 'Speed Limiter',
            description = 'Set max vehicle speed (km/h)',
            tab = 'vehicle',
            type = 'prompt',
            prompt = {
                title = 'Speed Limiter',
                fields = {
                    { name = 'speed', label = 'Speed (km/h)', placeholder = '120' },
                },
            },
        },
        {
            id = 'vehicle.clearSpeedLimit',
            label = 'Clear Speed Limit',
            description = 'Remove speed limiter',
            tab = 'vehicle',
            type = 'action',
        },
        {
            id = 'vehicle.torqueMultiplier',
            label = 'Torque Multiplier',
            description = 'Adjust vehicle torque',
            tab = 'vehicle',
            type = 'select',
            values = {
                { label = 'Normal', value = 1.0 },
                { label = '1.5x', value = 1.5 },
                { label = '2x', value = 2.0 },
                { label = '3x', value = 3.0 },
                { label = '5x', value = 5.0 },
                { label = '10x', value = 10.0 },
            },
        },
        {
            id = 'vehicle.powerMultiplier',
            label = 'Power Multiplier',
            description = 'Adjust vehicle power',
            tab = 'vehicle',
            type = 'select',
            values = {
                { label = 'Normal', value = 1.0 },
                { label = '1.5x', value = 1.5 },
                { label = '2x', value = 2.0 },
                { label = '3x', value = 3.0 },
                { label = '5x', value = 5.0 },
                { label = '10x', value = 10.0 },
            },
        },
        {
            id = 'vehicle.changePlate',
            label = 'Change Plate Text',
            description = 'Set custom license plate text',
            tab = 'vehicle',
            type = 'prompt',
            prompt = {
                title = 'Change Plate Text',
                fields = {
                    { name = 'plate', label = 'Plate Text', placeholder = 'ADMIN' },
                },
            },
        },
        {
            id = 'vehicle.bikeSeatbelt',
            label = 'Bike Seatbelt',
            description = 'Stay on bike during crashes',
            tab = 'vehicle',
            type = 'toggle',
        },
        {
            id = 'vehicle.maxMods',
            label = 'Max Performance Mods',
            description = 'Apply max performance upgrades',
            tab = 'vehicle',
            type = 'action',
        },
        {
            id = 'vehicle.adminCar',
            label = 'Admin Car',
            description = 'Save current vehicle to your QBX garage',
            tab = 'vehicle',
            type = 'action',
            framework = 'qbx',
        },
        {
            id = 'vehicle.giveKeys',
            label = 'Give Current Vehicle Keys',
            description = 'Give yourself keys for the vehicle you are in',
            tab = 'vehicle',
            type = 'action',
            framework = 'qbx',
        },

        {
            id = 'world.weather',
            label = 'Set Weather',
            description = 'Change global weather',
            tab = 'world',
            type = 'select',
            values = {
                { label = 'Extra Sunny', value = 'EXTRASUNNY' },
                { label = 'Clear', value = 'CLEAR' },
                { label = 'Clouds', value = 'CLOUDS' },
                { label = 'Smog', value = 'SMOG' },
                { label = 'Foggy', value = 'FOGGY' },
                { label = 'Overcast', value = 'OVERCAST' },
                { label = 'Rain', value = 'RAIN' },
                { label = 'Thunder', value = 'THUNDER' },
                { label = 'Clearing', value = 'CLEARING' },
                { label = 'Neutral', value = 'NEUTRAL' },
                { label = 'Blizzard', value = 'BLIZZARD' },
                { label = 'Snow', value = 'SNOW' },
                { label = 'Snowlight', value = 'SNOWLIGHT' },
                { label = 'Xmas', value = 'XMAS' },
                { label = 'Halloween', value = 'HALLOWEEN' },
            },
        },
        {
            id = 'world.time',
            label = 'Set Time',
            description = 'Change global time',
            tab = 'world',
            type = 'select',
            values = {
                { label = '00:00', value = 0 },
                { label = '01:00', value = 1 },
                { label = '02:00', value = 2 },
                { label = '03:00', value = 3 },
                { label = '04:00', value = 4 },
                { label = '05:00', value = 5 },
                { label = '06:00', value = 6 },
                { label = '07:00', value = 7 },
                { label = '08:00', value = 8 },
                { label = '09:00', value = 9 },
                { label = '10:00', value = 10 },
                { label = '11:00', value = 11 },
                { label = '12:00', value = 12 },
                { label = '13:00', value = 13 },
                { label = '14:00', value = 14 },
                { label = '15:00', value = 15 },
                { label = '16:00', value = 16 },
                { label = '17:00', value = 17 },
                { label = '18:00', value = 18 },
                { label = '19:00', value = 19 },
                { label = '20:00', value = 20 },
                { label = '21:00', value = 21 },
                { label = '22:00', value = 22 },
                { label = '23:00', value = 23 },
            },
        },
        {
            id = 'world.freezeTime',
            label = 'Freeze Time',
            description = 'Stop time progression',
            tab = 'world',
            type = 'toggle',
        },
        {
            id = 'world.blackout',
            label = 'Blackout',
            description = 'Toggle city blackout',
            tab = 'world',
            type = 'toggle',
        },
        {
            id = 'world.dynamicWeather',
            label = 'Dynamic Weather',
            description = 'Enable weather progression',
            tab = 'world',
            type = 'toggle',
        },
        {
            id = 'world.disableNpcs',
            label = 'Disable NPCs & Traffic',
            description = 'Remove all ambient peds and vehicles',
            tab = 'world',
            type = 'toggle',
        },
        {
            id = 'world.clearArea',
            label = 'Clear Area',
            description = 'Delete all entities in radius',
            tab = 'world',
            type = 'select',
            values = Config.ClearRadiusOptions,
        },
        {
            id = 'world.clearVehicles',
            label = 'Delete Vehicles',
            description = 'Delete nearby vehicles',
            tab = 'world',
            type = 'select',
            values = Config.ClearRadiusOptions,
        },
        {
            id = 'world.clearPeds',
            label = 'Delete Peds',
            description = 'Delete nearby peds',
            tab = 'world',
            type = 'select',
            values = Config.ClearRadiusOptions,
        },
        {
            id = 'world.clearObjects',
            label = 'Delete Objects',
            description = 'Delete nearby objects',
            tab = 'world',
            type = 'select',
            values = Config.ClearRadiusOptions,
        },
        {
            id = 'weapons.give',
            label = 'Give Weapon',
            description = 'Give a weapon by name',
            tab = 'weapons',
            type = 'select',
            values = Config.WeaponList,
        },
        {
            id = 'weapons.giveCustom',
            label = 'Give Weapon (Custom)',
            description = 'Give a weapon by custom name',
            tab = 'weapons',
            type = 'prompt',
            prompt = {
                title = 'Give Weapon (Custom)',
                fields = {
                    { name = 'weapon', label = 'Weapon', placeholder = 'weapon_carbinerifle' },
                },
            },
        },
        {
            id = 'weapons.giveAll',
            label = 'Give All Weapons',
            description = 'Give every weapon in the list',
            tab = 'weapons',
            type = 'action',
        },
        {
            id = 'weapons.removeAll',
            label = 'Remove All Weapons',
            description = 'Strip all weapons',
            tab = 'weapons',
            type = 'action',
            requiresConfirm = true,
        },
        {
            id = 'weapons.saveLoadout',
            label = 'Save Weapon Loadout',
            description = 'Save your current carried weapons and ammo',
            tab = 'weapons',
            type = 'prompt',
            prompt = {
                title = 'Save Weapon Loadout',
                fields = {
                    { name = 'name', label = 'Loadout name', placeholder = 'Patrol' },
                },
            },
        },
        {
            id = 'weapons.loadLoadout',
            label = 'Load Weapon Loadout',
            description = 'Restore a saved weapon loadout',
            tab = 'weapons',
            type = 'prompt',
            prompt = {
                title = 'Load Weapon Loadout',
                fields = {
                    { name = 'name', label = 'Loadout name', placeholder = 'Patrol' },
                },
            },
        },
        {
            id = 'weapons.deleteLoadout',
            label = 'Delete Weapon Loadout',
            description = 'Delete a saved weapon loadout',
            tab = 'weapons',
            type = 'prompt',
            prompt = {
                title = 'Delete Weapon Loadout',
                fields = {
                    { name = 'name', label = 'Loadout name', placeholder = 'Patrol' },
                },
            },
        },
        {
            id = 'weapons.infiniteAmmo',
            label = 'Infinite Ammo',
            description = 'Never run out of ammo',
            tab = 'weapons',
            type = 'toggle',
        },
        {
            id = 'weapons.setAmmo',
            label = 'Set Ammo',
            description = 'Set ammo for current weapon',
            tab = 'weapons',
            type = 'prompt',
            prompt = {
                title = 'Set Ammo',
                fields = {
                    { name = 'ammo', label = 'Ammo', placeholder = '250' },
                },
            },
        },
        {
            id = 'teleport.waypoint',
            label = 'Teleport to Waypoint',
            description = 'Teleport to current waypoint',
            tab = 'teleport',
            type = 'action',
        },
        {
            id = 'teleport.marker',
            label = 'Teleport to Marker',
            description = 'Teleport to map marker blip',
            tab = 'teleport',
            type = 'action',
        },
        {
            id = 'teleport.coords',
            label = 'Teleport to Coords',
            description = 'Teleport to specific coordinates',
            tab = 'teleport',
            type = 'prompt',
            prompt = {
                title = 'Teleport to Coords',
                fields = {
                    { name = 'x', label = 'X', placeholder = '0.0' },
                    { name = 'y', label = 'Y', placeholder = '0.0' },
                    { name = 'z', label = 'Z', placeholder = '0.0' },
                },
            },
        },
        {
            id = 'teleport.back',
            label = 'Teleport Back',
            description = 'Return to last location',
            tab = 'teleport',
            type = 'action',
        },
        {
            id = 'teleport.saveLocation',
            label = 'Save Location',
            description = 'Save current position',
            tab = 'teleport',
            type = 'prompt',
            prompt = {
                title = 'Save Teleport Location',
                fields = {
                    { name = 'name', label = 'Name', placeholder = 'MySpot' },
                },
            },
        },
        {
            id = 'teleport.loadLocation',
            label = 'Load Saved Location',
            description = 'Teleport to a saved location',
            tab = 'teleport',
            type = 'prompt',
            prompt = {
                title = 'Load Teleport Location',
                fields = {
                    { name = 'name', label = 'Name', placeholder = 'MySpot' },
                },
            },
        },
        {
            id = 'teleport.deleteLocation',
            label = 'Delete Saved Location',
            description = 'Delete a saved teleport location',
            tab = 'teleport',
            type = 'prompt',
            prompt = {
                title = 'Delete Teleport Location',
                fields = {
                    { name = 'name', label = 'Name', placeholder = 'MySpot' },
                },
            },
        },
        {
            id = 'dev.showCoords',
            label = 'Coordinate HUD',
            description = 'Display live coordinates on screen',
            tab = 'dev',
            type = 'toggle',
        },
        {
            id = 'dev.showSpeed',
            label = 'Speed HUD',
            description = 'Simple speed readout at chosen screen edge',
            tab = 'dev',
            type = 'toggle',
        },
        {
            id = 'options.speedHudUnits',
            label = 'Speed HUD Units',
            description = 'Miles or kilometers per hour',
            tab = 'dev',
            type = 'select',
            values = {
                { label = 'MPH', value = 'mph' },
                { label = 'KPH', value = 'kph' },
            },
        },
        {
            id = 'options.speedHudPosition',
            label = 'Speed HUD Position',
            description = 'Where the speed text anchors on screen',
            tab = 'dev',
            type = 'select',
            values = {
                { label = 'Top Left', value = 'top-left' },
                { label = 'Top Right', value = 'top-right' },
                { label = 'Top Middle', value = 'top-center' },
                { label = 'Bottom Left', value = 'bottom-left' },
                { label = 'Bottom Right', value = 'bottom-right' },
                { label = 'Bottom Middle', value = 'bottom-center' },
            },
        },
        {
            id = 'dev.noHud',
            label = 'Hide HUD',
            description = 'Toggle GTA HUD visibility',
            tab = 'dev',
            type = 'toggle',
        },
        {
            id = 'dev.nightVision',
            label = 'Night Vision',
            description = 'Toggle night vision effect',
            tab = 'dev',
            type = 'toggle',
        },
        {
            id = 'dev.thermalVision',
            label = 'Thermal Vision',
            description = 'Toggle thermal vision effect',
            tab = 'dev',
            type = 'toggle',
        },
        {
            id = 'dev.playerBlips',
            label = 'Show Player Blips',
            description = 'Show all players on the map',
            tab = 'dev',
            type = 'toggle',
        },
        {
            id = 'dev.takePhoto',
            label = 'Take Photo',
            description = 'Capture a screenshot and save it to the server photo folder',
            tab = 'recording',
            type = 'action',
        },
        {
            id = 'dev.openGallery',
            label = 'Open Gallery',
            description = 'Open the pause-menu gallery',
            tab = 'recording',
            type = 'action',
        },
        {
            id = 'dev.startRecording',
            label = 'Start Recording',
            description = 'Start GTA V clip recording (menu closes; reopen admin to stop or discard)',
            tab = 'recording',
            type = 'action',
        },
        {
            id = 'dev.stopRecording',
            label = 'Stop Recording',
            description = 'Stop and save the current clip (min. ~3s after start)',
            tab = 'recording',
            type = 'action',
        },
        {
            id = 'dev.discardRecording',
            label = 'Discard Recording',
            description = 'Stop and discard the current clip without saving',
            tab = 'recording',
            type = 'action',
        },
        {
            id = 'dev.openRockstarEditor',
            label = 'Rockstar Editor',
            description = 'Open Rockstar Editor to edit saved clips',
            tab = 'recording',
            type = 'action',
        },
        {
            id = 'dev.freecam',
            label = 'Freecam',
            description = 'Detached camera for inspecting vehicles, interiors, and props (disable before noclip)',
            tab = 'recording',
            type = 'toggle',
        },
        {
            id = 'dev.setStress',
            label = 'Set My Stress',
            description = 'Set your own stress level (0-100)',
            tab = 'dev',
            type = 'prompt',
            framework = 'qbx',
            prompt = {
                title = 'Set My Stress',
                fields = {
                    { name = 'value', label = 'Stress (0-100)', placeholder = '0' },
                },
            },
        },
        {
            id = 'dev.resetAllSettings',
            label = 'Reset & Reload UI',
            description = 'Restore defaults, then reload the admin UI',
            tab = 'dev',
            type = 'action',
            requiresConfirm = true,
        },
        {
            id = 'options.uiScale',
            label = 'UI Scale',
            description = 'Adjust admin menu scale',
            tab = 'options',
            type = 'select',
            values = {
                { label = 'Default', value = 1.0 },
                { label = 'Large', value = 1.15 },
                { label = 'Extra Large', value = 1.3 },
                { label = 'Ultra', value = 1.45 },
                { label = 'Maximum', value = 1.6 },
            },
        },
        {
            id = 'options.uiOpacity',
            label = 'UI Opacity',
            description = 'Adjust menu opacity',
            tab = 'options',
            type = 'select',
            values = {
                { label = '80%', value = 0.8 },
                { label = '90%', value = 0.9 },
                { label = '95%', value = 0.95 },
                { label = '100%', value = 1 },
            },
        },
        {
            id = 'options.menuPosition',
            label = 'Menu Position',
            description = 'Dock the menu to the side of the screen',
            tab = 'options',
            type = 'dock',
        },
        {
            id = 'options.doubleClickToRun',
            label = 'Double-Click to Run',
            description = 'Enable double-clicking on actions to execute them immediately',
            tab = 'options',
            type = 'toggle',
        },
        {
            id = 'options.showTargetInfo',
            label = 'Show Target Info',
            description = 'Display target info in header',
            tab = 'options',
            type = 'toggle',
        },
        {
            id = 'options.autoLoadSavedPed',
            label = 'Auto-Load Saved Ped',
            description = 'Automatically load your last saved MP Ped on spawn',
            tab = 'options',
            type = 'toggle',
        },
        {
            id = 'options.replacePersonalVehicle',
            label = 'Replace Previous Spawned Vehicle',
            description = 'When enabled, deletes the vehicle you are in before spawning from vehicle list, preview spawn, personal vehicles, or garage',
            tab = 'options',
            type = 'toggle',
        },
        {
            id = 'options.quitSessionInRockstarEditor',
            label = 'Quit Session Before Editor',
            description = 'Leave session before opening Rockstar Editor (avoids some session issues)',
            tab = 'recording',
            type = 'toggle',
        },
        {
            id = 'options.restorePedOnDeath',
            label = 'Restore Ped on Death',
            description = 'Restore your saved MP Ped appearance after respawning',
            tab = 'options',
            type = 'toggle',
        },
        {
            id = 'options.defaultToMpPed',
            label = 'Default to MP Ped',
            description = 'Use MP Freemode ped if no saved ped exists',
            tab = 'options',
            type = 'toggle',
        },
        -- ================================================================
        -- INVENTORY (QBX / ox_inventory)
        -- ================================================================
        {
            id = 'inventory.giveItem',
            label = 'Give Item',
            description = 'Give an item to a player from the full item list',
            tab = 'inventory',
            type = 'action',
            framework = 'qbx',
        },

        -- ================================================================
        -- GARAGE (QBX / qbx_vehicles)
        -- ================================================================
        {
            id = 'garage.spawnVehicle',
            label = 'My Garage',
            description = 'Spawn a personal vehicle from your QBX garage',
            tab = 'garage',
            type = 'action',
            framework = 'qbx',
        },

        -- ================================================================
        -- SERVER
        -- ================================================================
        {
            id = 'server.resources',
            label = 'Resource Manager',
            description = 'Manage server resources (ensure, start, stop, restart)',
            tab = 'server',
            type = 'action',
        },
        {
            id = 'server.pullStash',
            label = 'Pull Stash',
            description = 'Open a stash by name (ox_inventory)',
            tab = 'server',
            type = 'action',
            framework = 'qbx',
        },
        {
            id = 'server.refresh',
            label = 'Refresh Resources',
            description = 'Refresh resource list and discover new folders',
            tab = 'server',
            type = 'action',
        },
    }
}

return EsAdminActions
