-- Reviewed official GTA Online clothing used by the modular appearance
-- generator. Drawable IDs are the official global indexes from the source
-- catalogs; the client resolves them to collection-local indexes at runtime.
--
-- Names: root-cause/v-clothingnames @ 84020cfa80b1a2fdc86f0e8eb438d313f343c015
-- Torsos: root-cause/v-besttorso     @ a2eba9f862baf7c6da34a4b5d1bd36a4abbf8e03
-- Reviewed: 2026-08-18. Costume, holiday, underwear and novelty pieces were
-- excluded. Every top includes the torso recommended by v-besttorso.

AppearanceCatalog = AppearanceCatalog or {}

local P = { 'polished' }
local C = { 'casual' }
local S = { 'street' }
local PC = { 'polished', 'casual' }
local CS = { 'casual', 'street' }

local function color(name, texture)
    return { name = name, texture = texture }
end

local function top(id, drawable, torso, styles, neutral, tonal, varied)
    return {
        id = id,
        drawable = drawable,
        torso = torso,
        styles = styles,
        variants = { neutral = { neutral }, tonal = { tonal }, varied = { varied } },
    }
end

local function garment(id, drawable, styles, neutral, tonal, varied)
    return {
        id = id,
        drawable = drawable,
        styles = styles,
        variants = { neutral = { neutral }, tonal = { tonal }, varied = { varied } },
    }
end

AppearanceCatalog.male = {
    tops = {
        top('double_suit', 20, 1, P, color('Charcoal pinstripe double suit', 2), color('Navy pinstripe double suit', 1), color('Classic ivory double suit', 0)),
        top('sports_coat', 23, 1, P, color('White sports coat', 3), color('Navy sports coat', 2), color('Lilac sports coat', 1)),
        top('smart_jacket', 24, 1, PC, color('Light gray jacket', 0), color('Subtle blue jacket', 4), color('Brown jacket', 5)),
        top('tucked_shirt', 26, 11, P, color('Gray plaid tucked shirt', 9), color('Navy tucked shirt', 0), color('Ash tucked shirt', 2)),
        top('double_breasted', 27, 1, P, color('Black double-breasted jacket', 0), color('Blue double-breasted jacket', 2), color('Gray double-breasted jacket', 1)),
        top('tailored_jacket', 28, 1, P, color('Black tailored jacket', 0), color('Blue tailored jacket', 2), color('Gray tailored jacket', 1)),
        top('smooth_fitted', 30, 1, P, color('Black smooth fitted jacket', 0), color('Navy smooth fitted jacket', 2), color('Teal smooth fitted jacket', 3)),
        top('sharp_fitted', 32, 1, P, color('Black sharp fitted jacket', 0), color('Navy sharp fitted jacket', 2), color('Teal sharp fitted jacket', 3)),
        top('combat_top', 49, 4, S, color('Black combat top', 0), color('Tan combat top', 3), color('Charcoal combat top', 2)),
        top('combat_sweater', 50, 4, S, color('Black combat sweater', 0), color('Tan combat sweater', 3), color('Charcoal combat sweater', 2)),
        top('hooded_jacket', 68, 4, CS, color('Black hooded jacket', 0), color('Navy hooded jacket', 4), color('Dark gray hooded jacket', 2)),
        top('leather_fur_jacket', 70, 4, CS, color('Black leather fur jacket', 2), color('Brown leather fur jacket', 0), color('Fall leather fur jacket', 6)),
        top('wool_coat', 72, 4, PC, color('Gray wool coat', 1), color('Navy wool coat', 3), color('Black wool coat', 2)),
        top('bomber', 74, 4, CS, color('Black SN bomber', 2), color('Brown diamond bomber', 4), color('Classic SN bomber', 0)),
        top('zipped_bomber', 75, 6, CS, color('Black SN zipped bomber', 2), color('Brown zipped bomber', 4), color('Classic SN zipped bomber', 0)),
        top('trench_coat', 76, 14, P, color('Black trench coat', 1), color('Navy trench coat', 2), color('Gray trench coat', 3)),
        top('overcoat', 77, 4, P, color('Gray overcoat', 0), color('Navy overcoat', 2), color('Beige overcoat', 1)),
        top('print_sweater', 78, 6, CS, color('Black geo-print sweater', 2), color('Brown print sweater', 7), color('Hound print sweater', 4)),
        top('loose_polo', 82, 0, PC, color('Black loose polo', 2), color('Blue-stripe loose polo', 6), color('Gray loose polo', 0)),
        top('sport_hoodie', 86, 4, CS, color('Black sport hoodie', 0), color('Blue sport hoodie', 3), color('Gray sport hoodie', 1)),
        top('varsity_jacket', 87, 4, S, color('Black varsity jacket', 2), color('Blue varsity jacket', 10), color('Gray varsity jacket', 5)),
        top('utility_tee', 97, 0, CS, color('Beige T-shirt', 0), color('Khaki T-shirt', 1), color('Beige T-shirt', 0)),
        top('continental_jacket', 100, 1, P, color('White continental jacket', 0), color('Navy continental jacket', 1), color('Lilac continental jacket', 3)),
        top('check_double_suit', 119, 1, P, color('Gray check double suit', 4), color('Blue check double suit', 0), color('Dusk check double suit', 2)),
    },
    bottoms = {
        garment('smart_regular', 22, PC, color('Light gray regular pants', 0), color('Subtle blue regular pants', 4), color('Brown regular pants', 5)),
        garment('skinny_suit', 24, P, color('Black skinny suit pants', 0), color('Navy skinny suit pants', 2), color('Teal skinny suit pants', 3)),
        garment('regular_suit', 25, P, color('Gray regular suit pants', 1), color('Navy regular suit pants', 2), color('Teal regular suit pants', 3)),
        garment('slim_fit', 28, PC, color('Black slim-fit pants', 0), color('Olive slim-fit pants', 4), color('Gray slim-fit pants', 3)),
        garment('striped_chinos', 29, P, color('Thin striped chinos', 0), color('Thin striped chinos', 0), color('Wide striped chinos', 1)),
        garment('scruffy_suit', 37, P, color('Gray scruffy suit pants', 0), color('Blue scruffy suit pants', 3), color('Black scruffy suit pants', 2)),
        garment('flight_pants', 41, S, color('Black flight pants', 0), color('Black flight pants', 0), color('Black flight pants', 0)),
        garment('loose_jeans', 43, CS, color('Black loose jeans', 1), color('Blue loose jeans', 0), color('Blue loose jeans', 0)),
        garment('tracksuit_pants', 55, CS, color('Black tracksuit pants', 0), color('Navy tracksuit pants', 2), color('Teal tracksuit pants', 3)),
        garment('check_suit_pants', 60, P, color('Gray check suit pants', 4), color('Blue check suit pants', 0), color('Dusk check suit pants', 2)),
        garment('work_shorts', 62, C, color('Black work shorts', 0), color('Blue work shorts', 2), color('Khaki work shorts', 3)),
        garment('classic_jeans', 63, C, color('Classic blue jeans', 0), color('Classic blue jeans', 0), color('Classic blue jeans', 0)),
        garment('modern_tracksuit', 64, CS, color('Gray tracksuit pants', 8), color('Blue tracksuit pants', 0), color('Burgundy tracksuit pants', 1)),
        garment('plain_biker', 71, C, color('Black plain pants', 0), color('Chocolate plain pants', 2), color('Worn black plain pants', 3)),
        garment('padded_biker', 73, S, color('Black padded pants', 0), color('Chocolate padded pants', 2), color('Worn black padded pants', 3)),
        garment('ribbed_denim', 75, CS, color('Black ribbed jeans', 7), color('Indigo ribbed jeans', 0), color('Faded ribbed jeans', 2)),
        garment('roadworn_denim', 76, CS, color('Black roadworn jeans', 7), color('Navy roadworn jeans', 3), color('Faded roadworn jeans', 2)),
        garment('low_crotch', 78, S, color('Black low-crotch pants', 2), color('Chocolate low-crotch pants', 0), color('Charcoal low-crotch pants', 5)),
        garment('tapered_low_crotch', 82, S, color('Black tapered pants', 4), color('Navy tapered pants', 0), color('Classic tapered pants', 2)),
        garment('leather_jeans', 83, S, color('Black leather jeans', 0), color('Brown leather jeans', 3), color('Black leather jeans', 0)),
    },
    shoes = {
        garment('toe_oxfords', 18, P, color('Black-toe Oxfords', 0), color('Black-toe Oxfords', 0), color('White-toe Oxfords', 1)),
        garment('two_tone_oxfords', 20, P, color('Gray two-tone Oxfords', 5), color('Chocolate Oxfords', 0), color('Ash Oxfords', 4)),
        garment('slip_ons', 21, PC, color('Black slip-ons', 0), color('Navy slip-ons', 7), color('Copper slip-ons', 5)),
        garment('dlc_canvas', 22, C, color('Gray two-tone canvas shoes', 5), color('Sky-blue canvas shoes', 0), color('Checked canvas shoes', 6)),
        garment('wingtips', 23, P, color('Black wingtips', 6), color('Navy wingtips', 1), color('Gentleman wingtips', 7)),
        garment('flight_boots', 24, S, color('Black flight boots', 0), color('Black flight boots', 0), color('Black flight boots', 0)),
        garment('tactical_boots', 25, S, color('Black tactical boots', 0), color('Black tactical boots', 0), color('Black tactical boots', 0)),
        garment('studded_sneakers', 28, CS, color('Black studded sneakers', 1), color('Blue studded sneakers', 5), color('White studded sneakers', 0)),
        garment('driving_loafers', 30, PC, color('Gray driving loafers', 1), color('Dual driving loafers', 0), color('Dual driving loafers', 0)),
        garment('calypso_runners', 31, CS, color('Calypso runners', 0), color('Calypso runners', 0), color('Buzz runners', 1)),
        garment('hi_top_sneakers', 32, CS, color('Black high-top sneakers', 0), color('Black high-top sneakers', 0), color('Dual high-top sneakers', 2)),
        garment('walking_boots', 35, C, color('Tan walking boots', 0), color('Khaki walking boots', 1), color('Tan walking boots', 0)),
        garment('leather_loafers', 36, PC, color('Black leather loafers', 3), color('Brown leather loafers', 2), color('Sienna leather loafers', 0)),
        garment('tip_oxfords', 40, P, color('Gray-tip Oxfords', 4), color('Blue-tip Oxfords', 0), color('Dusk-tip Oxfords', 2)),
        garment('canvas_slip_ons', 42, PC, color('Black canvas slip-ons', 1), color('Blue canvas slip-ons', 4), color('Striped canvas slip-ons', 5)),
        garment('ankle_boots', 43, CS, color('Black ankle boots', 3), color('Blue ankle boots', 4), color('Denim ankle boots', 2)),
        garment('laceup_boots', 50, CS, color('Black lace-up boots', 0), color('Chocolate lace-up boots', 2), color('Worn black lace-up boots', 3)),
        garment('slack_boots', 53, CS, color('Black slack boots', 0), color('Chocolate slack boots', 2), color('Worn black slack boots', 3)),
        garment('plain_high_tops', 57, CS, color('Silver plain high-tops', 6), color('Blue plain high-tops', 2), color('Bronze plain high-tops', 3)),
        garment('tech_boots', 60, S, color('Black tech boots', 0), color('Brown tech boots', 2), color('Tawny tech boots', 4)),
        garment('moc_toe_boots', 65, CS, color('Black moc-toe boots', 1), color('Chocolate moc-toe boots', 3), color('Classic moc-toe boots', 0)),
        garment('trail_shoes', 72, S, color('Black and sand trail shoes', 1), color('Black and blue trail shoes', 2), color('Mono trail shoes', 0)),
        garment('retro_sneakers', 93, CS, color('Grayscale retro sneakers', 11), color('Blue retro sneakers', 0), color('Two-tone retro sneakers', 5)),
        garment('uniform_boots', 96, S, color('Heavy uniform boots', 0), color('Heavy uniform boots', 0), color('Heavy uniform boots', 0)),
    },
}

AppearanceCatalog.female = {
    tops = {
        top('blazer', 25, 6, P, color('Cream blazer', 2), color('Blue suede blazer', 4), color('Burgundy blazer', 7)),
        top('blouse', 27, 0, PC, color('Black blouse', 1), color('Tan blouse', 2), color('Gray striped blouse', 3)),
        top('tailored_vest', 28, 0, P, color('Gray vest', 1), color('Navy vest', 2), color('Black vest', 3)),
        top('cropped_biker', 35, 5, CS, color('Silver cropped biker jacket', 10), color('Dark brown cropped biker jacket', 4), color('Mustard cropped biker jacket', 2)),
        top('combat_top', 42, 3, S, color('Black combat top', 0), color('Tan combat top', 3), color('Charcoal combat top', 2)),
        top('combat_sweater', 43, 3, S, color('Black combat sweater', 0), color('Tan combat sweater', 3), color('Charcoal combat sweater', 2)),
        top('rolled_shirt', 56, 14, PC, color('Black rolled shirt', 0), color('Black rolled shirt', 0), color('Black rolled shirt', 0)),
        top('fitted_tux', 58, 3, P, color('Black fitted tux', 0), color('Navy fitted tux', 2), color('Teal fitted tux', 3)),
        top('hooded_jacket', 62, 3, CS, color('Black hooded jacket', 0), color('Navy hooded jacket', 4), color('Dark gray hooded jacket', 2)),
        top('peacoat', 64, 5, PC, color('Black peacoat', 1), color('Navy peacoat', 2), color('Gray peacoat', 3)),
        top('leather_fur_jacket', 65, 5, CS, color('Black leather fur jacket', 3), color('Brown leather fur jacket', 1), color('Fall leather fur jacket', 6)),
        top('belted_jacket', 66, 5, PC, color('Black belted jacket', 0), color('Brown belted jacket', 1), color('Teal belted jacket', 3)),
        top('trench_coat', 70, 5, P, color('Black trench coat', 1), color('Navy trench coat', 2), color('Gray trench coat', 3)),
        top('print_sweater', 71, 1, CS, color('Black geo-print sweater', 2), color('Brown print sweater', 7), color('Hound print sweater', 4)),
        top('loose_tank', 74, 15, CS, color('Black loose tank', 1), color('White loose tank', 0), color('Gray loose tank', 2)),
        top('sport_hoodie', 78, 3, CS, color('Black sport hoodie', 0), color('Blue sport hoodie', 6), color('Lilac sport hoodie', 2)),
        top('varsity_jacket', 81, 3, S, color('Black varsity jacket', 2), color('Blue varsity jacket', 10), color('Gray varsity jacket', 5)),
        top('utility_tee', 88, 14, CS, color('Beige T-shirt', 0), color('Khaki T-shirt', 1), color('Beige T-shirt', 0)),
        top('continental_jacket', 91, 3, P, color('White continental jacket', 0), color('Navy continental jacket', 1), color('Lilac continental jacket', 3)),
        top('shiny_jacket', 93, 3, P, color('Black shiny jacket', 2), color('Blue shiny jacket', 1), color('Black shiny jacket', 2)),
        top('work_shirt', 119, 14, PC, color('Black work shirt', 2), color('Navy work shirt', 1), color('White work shirt', 0)),
    },
    bottoms = {
        garment('tailored_suit', 23, P, color('Gray woven suit pants', 4), color('Blue suit pants', 1), color('Olive suit pants', 5)),
        garment('panel_pencil', 24, P, color('Gray panel pencil skirt', 3), color('Blue pencil skirt', 1), color('Houndstooth pencil skirt', 2)),
        garment('denim_shorts', 25, C, color('Black denim shorts', 6), color('Navy denim shorts', 0), color('Blue denim shorts', 2)),
        garment('leggings', 27, CS, color('Black leggings', 0), color('Navy leggings', 13), color('Gray leggings', 1)),
        garment('combat_pants', 30, S, color('Black combat pants', 0), color('Tan combat pants', 3), color('Charcoal combat pants', 2)),
        garment('heist_pants', 32, S, color('Black heist pants', 0), color('Black heist pants', 0), color('Black heist pants', 0)),
        garment('pencil_skirt', 36, P, color('Gray pencil skirt', 0), color('Blue pencil skirt', 3), color('Black pencil skirt', 2)),
        garment('regular_suit', 37, PC, color('Black regular suit pants', 0), color('Navy regular suit pants', 2), color('Teal regular suit pants', 3)),
        garment('scruffy_suit', 41, P, color('Gray scruffy suit pants', 0), color('Blue scruffy suit pants', 3), color('Black scruffy suit pants', 2)),
        garment('flight_pants', 42, S, color('Black flight pants', 0), color('Black flight pants', 0), color('Black flight pants', 0)),
        garment('leather_zippers', 43, CS, color('Black leather zip pants', 0), color('Brown leather zip pants', 2), color('Burgundy leather zip pants', 4)),
        garment('skinny_cuts', 44, CS, color('Black skinny-cut pants', 0), color('Brown skinny-cut pants', 2), color('Burgundy skinny-cut pants', 4)),
        garment('baggy_cargo', 45, S, color('Black baggy cargo pants', 1), color('Khaki baggy cargo pants', 0), color('Gray baggy cargo pants', 3)),
        garment('battle_pants', 48, S, color('Tan battle pants', 0), color('Khaki battle pants', 1), color('Tan battle pants', 0)),
        garment('utility_pants', 49, S, color('Tan utility pants', 0), color('Khaki utility pants', 1), color('Tan utility pants', 0)),
        garment('tracksuit_pants', 58, CS, color('Black tracksuit pants', 0), color('Navy tracksuit pants', 2), color('Teal tracksuit pants', 3)),
        garment('fitted_chinos', 64, PC, color('Black fitted chinos', 1), color('Khaki fitted chinos', 2), color('Gray fitted chinos', 3)),
        garment('high_waisted', 65, PC, color('Black high-waisted pants', 0), color('Black high-waisted pants', 0), color('Gray high-waisted pants', 2)),
        garment('modern_tracksuit', 66, S, color('Gray tracksuit pants', 8), color('Blue tracksuit pants', 0), color('Burgundy tracksuit pants', 1)),
        garment('ribbed_denim', 73, C, color('Black ribbed jeans', 1), color('Deep-blue ribbed jeans', 2), color('Stonewash ribbed jeans', 3)),
        garment('roadworn_denim', 74, C, color('Black roadworn jeans', 1), color('Deep-blue roadworn jeans', 2), color('Stonewash roadworn jeans', 3)),
        garment('plain_biker', 75, C, color('Black plain pants', 0), color('Mocha plain pants', 1), color('Black plain pants', 0)),
        garment('quilted_biker', 76, C, color('Black quilted pants', 0), color('Mocha quilted pants', 1), color('Black quilted pants', 0)),
        garment('low_crotch', 80, S, color('Black low-crotch pants', 2), color('Chocolate low-crotch pants', 0), color('Charcoal low-crotch pants', 5)),
        garment('leather_low_crotch', 81, S, color('Black leather pants', 0), color('Black leather pants', 0), color('Black leather pants', 0)),
        garment('tapered_low_crotch', 84, S, color('Black tapered pants', 4), color('Navy tapered pants', 0), color('Classic tapered pants', 2)),
        garment('leather_jeans', 85, S, color('Black leather jeans', 0), color('Brown leather jeans', 3), color('Black leather jeans', 0)),
    },
    shoes = {
        garment('platforms', 19, C, color('Olive platforms', 0), color('Blue platforms', 11), color('Earth platforms', 2)),
        garment('patent_heels', 20, PC, color('Gray patent heels', 3), color('Blue patent heels', 6), color('Burgundy patent heels', 2)),
        garment('knee_high_boots', 21, P, color('Gray-accent knee-high boots', 9), color('Coffee knee-high boots', 6), color('Chestnut knee-high boots', 1)),
        garment('folded_boots', 22, PC, color('Black folded boots', 1), color('Coffee folded boots', 2), color('Gray folded boots', 4)),
        garment('flight_boots', 24, S, color('Black flight boots', 0), color('Black flight boots', 0), color('Black flight boots', 0)),
        garment('tactical_boots', 25, S, color('Black tactical boots', 0), color('Black tactical boots', 0), color('Black tactical boots', 0)),
        garment('backside_sneakers', 27, CS, color('All-black backside sneakers', 0), color('All-black backside sneakers', 0), color('All-black backside sneakers', 0)),
        garment('black_sports', 28, CS, color('All-black sports shoes', 0), color('All-black sports shoes', 0), color('All-black sports shoes', 0)),
        garment('dlc_oxfords', 29, P, color('All-black Oxfords', 0), color('Brown Oxfords', 2), color('White Oxfords', 1)),
        garment('studded_boots', 30, S, color('Leather studded boots', 0), color('Leather studded boots', 0), color('Leather studded boots', 0)),
        garment('calypso_runners', 32, CS, color('Calypso runners', 0), color('Calypso runners', 0), color('Buzz runners', 1)),
        garment('canvas_snugs', 33, CS, color('Black canvas shoes', 1), color('Blue canvas shoes', 5), color('White canvas shoes', 3)),
        garment('walking_boots', 36, C, color('Tan walking boots', 0), color('Khaki walking boots', 1), color('Tan walking boots', 0)),
        garment('leather_loafers', 37, PC, color('Black leather loafers', 3), color('Brown leather loafers', 2), color('Sienna leather loafers', 0)),
        garment('rounded_heels', 42, PC, color('Black rounded heels', 2), color('Blue rounded heels', 3), color('Nude rounded heels', 0)),
        garment('sneaker_wedges', 43, CS, color('Black sneaker wedges', 1), color('Blue sneaker wedges', 5), color('White sneaker wedges', 3)),
        garment('sneaker_boots', 44, CS, color('Black sneaker boots', 1), color('Blue sneaker boots', 5), color('White sneaker boots', 3)),
        garment('laceup_boots', 51, CS, color('Black lace-up boots', 0), color('Chocolate lace-up boots', 2), color('Worn black lace-up boots', 3)),
        garment('slack_boots', 54, CS, color('Black slack boots', 0), color('Chocolate slack boots', 2), color('Worn black slack boots', 3)),
        garment('calf_boots', 56, PC, color('Black calf boots', 0), color('Tan calf boots', 2), color('Ox-blood calf boots', 1)),
        garment('plain_high_tops', 60, CS, color('Silver plain high-tops', 6), color('Blue plain high-tops', 2), color('Bronze plain high-tops', 3)),
        garment('tech_boots', 63, S, color('Black tech boots', 0), color('Brown tech boots', 2), color('Tawny tech boots', 4)),
        garment('moc_toe_boots', 68, CS, color('Black moc-toe boots', 1), color('Chocolate moc-toe boots', 3), color('Classic moc-toe boots', 0)),
        garment('trail_shoes', 75, S, color('Black and sand trail shoes', 1), color('Black and blue trail shoes', 2), color('Mono trail shoes', 0)),
        garment('retro_sneakers', 96, CS, color('Grayscale retro sneakers', 11), color('Blue retro sneakers', 0), color('Two-tone retro sneakers', 5)),
        garment('uniform_boots', 100, S, color('Heavy uniform boots', 0), color('Heavy uniform boots', 0), color('Heavy uniform boots', 0)),
    },
}

-- Later-life wardrobe expansion. Names and torsos use the pinned sources above.
-- IDs/textures match the build-3407 index. In-game fit validation remains user-run.
local function expanded(id, drawable, torso, styles, neutral, tonal, varied)
    return { id = id, drawable = drawable, torso = torso, styles = styles,
        variants = { neutral = neutral, tonal = tonal, varied = varied } }
end
for _, entry in ipairs({
    expanded('office', 349, 1, { 'polished', 'nightlife' },
        { color('White Office', 0), color('Black Office', 3), color('Stone Office', 6) },
        { color('Navy Office', 2), color('Beige Office', 4), color('Ivory Office', 5) },
        { color('Berry Office', 7), color('Ash Office', 8), color('Gray Office', 9) }),
    expanded('office_open', 348, 1, { 'polished', 'nightlife' },
        { color('White Office Unbuttoned', 0), color('Black Office Unbuttoned', 3), color('Stone Office Unbuttoned', 6) },
        { color('Navy Office Unbuttoned', 2), color('Beige Office Unbuttoned', 4), color('Ivory Office Unbuttoned', 5) },
        { color('Berry Office Unbuttoned', 7), color('Ash Office Unbuttoned', 8), color('Gray Office Unbuttoned', 9) }),
    expanded('brand_polo', 350, 0, { 'polished', 'casual', 'resort', 'designer' },
        { color('White B Polo Shirt', 1), color('White FB Polo Shirt', 3), color('White Bigness Polo Shirt', 5) },
        { color('Purple B Polo Shirt', 0), color('Purple FB Polo Shirt', 2), color('Purple Bigness Polo Shirt', 4) },
        { color('Purple B Polo Shirt', 0), color('Purple FB Polo Shirt', 2), color('Purple Bigness Polo Shirt', 4) }),
    expanded('revere', 405, 198, { 'polished', 'resort', 'nightlife' },
        { color('Black Revere Collar', 0), color('Dark Gray Revere Collar', 1), color('Ice Revere Collar', 3) },
        { color('Beige Revere Collar', 4), color('Chocolate Revere Collar', 5), color('Burgundy Revere Collar', 6) },
        { color('Hot Pink Revere Collar', 7), color('Scarlet Revere Collar', 8), color('Orange Revere Collar', 9) }),
    expanded('cardigan', 423, 4, { 'polished', 'casual', 'nightlife' },
        { color('Black Cardigan', 0), color('Dark Gray Cardigan', 1), color('Ice Cardigan', 3) },
        { color('Beige Cardigan', 4), color('Chocolate Cardigan', 5), color('Burgundy Cardigan', 6) },
        { color('Hot Pink Cardigan', 7), color('Scarlet Cardigan', 8), color('Tangerine Cardigan', 9) }),
    expanded('designer_cardigan', 442, 4, { 'polished', 'designer', 'nightlife' },
        { color('Black Blagueurs Cardigan', 0), color('White Blagueurs Cardigan', 3) },
        { color('Blue Blagueurs Cardigan', 1), color('Blue DS Panthers Cardigan', 4), color('Blue DS Tiger Cardigan', 6) },
        { color('Red Blagueurs Cardigan', 2), color('Red DS Panthers Cardigan', 5), color('Red DS Tiger Cardigan', 7) }),
    expanded('chore', 388, 4, { 'polished', 'casual', 'utility' },
        { color('Ash Chore', 1), color('Gray Chore', 2), color('Black Chore', 3) },
        { color('Beige Chore', 4), color('Navy Chore', 5), color('Olive Chore', 6) },
        { color('Ice Chore', 0), color('Pink Chore', 7) }),
    expanded('double_shirt', 341, 4, { 'casual', 'street', 'utility' },
        { color('Black Double Shirt', 0), color('Gray Double Shirt', 1), color('White Double Shirt', 2) },
        { color('Navy Double Shirt', 3), color('Tan Double Shirt', 4), color('Khaki Double Shirt', 5) },
        { color('Ivory Double Shirt', 6), color('Off White Double Shirt', 7) }),
    expanded('pullover', 384, 4, { 'casual', 'street', 'sport' },
        { color('Black Pullover Hoodie', 0), color('Dark Gray Pullover Hoodie', 1), color('Light Gray Pullover Hoodie', 2), color('White Pullover Hoodie', 3) },
        { color('Beige Pullover Hoodie', 4), color('Brown Pullover Hoodie', 5), color('Maroon Pullover Hoodie', 6) },
        { color('Hot Pink Pullover Hoodie', 7), color('Red Pullover Hoodie', 8), color('Orange Pullover Hoodie', 9) }),
    expanded('brand_hoodie', 262, 4, { 'street', 'designer' },
        { color('Gray Sports Blagueurs Hoodie', 0), color('Black Sports Blagueurs Hoodie', 1), color('White College Blagueurs Hoodie', 2), color('Gray College Blagueurs Hoodie', 3) },
        { color('Spotted Dark GÃ¼ffy Hoodie', 6), color('Blue Leaves GÃ¼ffy Hoodie', 8) },
        { color('Graffiti Black GÃ¼ffy Hoodie', 4), color('Sprayed Green GÃ¼ffy Hoodie', 5), color('Neon Leaves GÃ¼ffy Hoodie', 7) }),
    expanded('casino_bomber', 298, 4, { 'street', 'designer', 'nightlife' },
        { color('Black Bigness Bomber', 0), color('White Bigness Bomber', 1), color('Black Broker Coin Bomber', 2), color('White Broker Coin Bomber', 3) },
        { color('Teal Broker Coin Bomber', 6), color('Black SC Broker Bomber', 7) },
        { color('Red Broker Coin Bomber', 4), color('Purple Broker Coin Bomber', 5) }),
    expanded('zipped_bigness', 343, 4, { 'casual', 'street', 'designer' },
        { color('Black Bigness Bomber Zipped', 0), color('Black 22 Bomber Zipped', 2), color('Black Detail Bomber Zipped', 3) },
        { color('Black Bigness Bomber Zipped', 0), color('Black Trickster Bomber Zipped', 5) },
        { color('Yellow Bigness Bomber Zipped', 1), color('Yellow Detail Bomber Zipped', 4), color('Yellow Trickster Bomber Zipped', 6) }),
    expanded('broker_puffer', 309, 1, { 'street', 'designer' },
        { color('Black Broker Puffer', 1), color('Black GÃ¼ffy Spray Puffer', 6) },
        { color('Maroon Broker Puffer', 0), color('Teal Broker Puffer', 2), color('Green FB Puffer', 3) },
        { color('Purple FB Puffer', 4), color('Yellow FB Puffer', 5), color('Turquoise GÃ¼ffy Spray Puffer', 7) }),
    expanded('track_top', 332, 4, { 'sport', 'casual' },
        { color('Cream Sports Track Top', 0), color('Gray Heat Sports Track Top', 1), color('White Heat Sports Track Top', 6) },
        { color('Orange Prolaps Sports Track Top', 8), color('Yellow Prolaps Sports Track Top', 9) },
        { color('Mustard Heat Sports Track Top', 2), color('Purple Heat Sports Track Top', 3), color('Orange Heat Sports Track Top', 4), color('Pink Heat Sports Track Top', 5), color('Cyan Heat Sports Track Top', 7) }),
    expanded('racing', 371, 4, { 'biker', 'street' },
        { color('Black Bravado Modern Racing', 0), color('Dark Dinka Modern Racing', 4) },
        { color('Blue Bravado Modern Racing', 1), color('Blue Dinka Modern Racing', 7) },
        { color('Fade Broker Modern Racing', 2), color('Yellow Vapid Modern Racing', 3), color('Light Dinka Modern Racing', 5), color('Red Dinka Modern Racing', 6) }),
    expanded('retro_racing', 378, 12, { 'biker', 'street' },
        { color('White Globe Oil Retro Racing', 1), color('Black Crowex Retro Racing', 2) },
        { color('Green Crowex Retro Racing', 3), color('Blue Atomic Retro Racing', 5), color('Blue Redwood Retro Racing', 6) },
        { color('Red Globe Oil Retro Racing', 0), color('Yellow Atomic Retro Racing', 4), color('Red Redwood Retro Racing', 7) }),
    expanded('leather_bomber', 379, 4, { 'biker', 'casual', 'nightlife' },
        { color('Mono Leather Bomber', 0) },
        { color('Dark Tan Leather Bomber', 2), color('Dark Green Leather Bomber', 3), color('Dark Nut Leather Bomber', 4), color('Navy Blue Leather Bomber', 6) },
        { color('Ox Blood Leather Bomber', 1), color('Orange Tan Leather Bomber', 5), color('Red Leather Bomber', 7) }),
    expanded('light_biker', 403, 4, { 'biker', 'nightlife' },
        { color('Black Light Biker', 0), color('Gray Light Biker', 1), color('Ash Light Biker', 2), color('Ice Light Biker', 3) },
        { color('Ox Blood Light Biker', 4), color('Dark Green Light Biker', 6) },
        { color('Scarlet Light Biker', 5), color('Red Light Biker', 7) }),
    expanded('field_blouson', 244, 14, { 'utility' },
        { color('Khaki Tactical Blouson', 0), color('Green Tactical Blouson', 1) },
        { color('Khaki Tactical Blouson', 0), color('Green Tactical Blouson', 1) },
        { color('Grayscale Tactical Blouson', 2), color('Dazzle Tactical Blouson', 3) }),
    expanded('waterproof', 296, 4, { 'utility', 'street' },
        { color('Black Bigness Waterproof', 0) },
        { color('Black Bigness Waterproof', 0) },
        { color('Cyan Bigness Waterproof', 1), color('Magenta Bigness Waterproof', 2), color('Red Bigness Waterproof', 3) }),
    expanded('botanical', 354, 11, { 'resort' },
        { color('Black Botanical Shortsleeve', 1), color('Black Blossom Shortsleeve', 3) },
        { color('Blue Blossom Shortsleeve', 2), color('Blue Blooming Shortsleeve', 4), color('Green Floral Shortsleeve', 6) },
        { color('Red Botanical Shortsleeve', 0), color('Orange Blooming Shortsleeve', 5), color('Cream Floral Shortsleeve', 7) }),
    expanded('palms', 406, 198, { 'resort', 'nightlife' },
        { color('Charcoal Floral Revere Collar', 2), color('Charcoal Palms Revere Collar', 4) },
        { color('Green Palms Revere Collar', 0), color('Cool Sunset Revere Collar', 6) },
        { color('Blush Palms Revere Collar', 1), color('Red Floral Revere Collar', 3), color('Pink Palms Revere Collar', 5), color('Warm Sunset Revere Collar', 7) }),
}) do AppearanceCatalog.male.tops[#AppearanceCatalog.male.tops + 1] = entry end
for _, entry in ipairs({
    expanded('chain', 102, nil, { 'street', 'biker' },
        { color('Black Chain Pants', 0), color('Gray Chain Pants', 1), color('White Chain Pants', 2) },
        { color('Brown Chain Pants', 3), color('Tan Chain Pants', 4), color('Beige Chain Pants', 5) },
        { color('Gray Camo Chain Pants', 6), color('Green Camo Chain Pants', 7) }),
    expanded('leather_stitch', 105, nil, { 'biker', 'nightlife' },
        { color('Black Leather Stitch Pants', 0), color('Gray Leather Stitch Pants', 7) },
        { color('Dark Red Leather Stitch Pants', 3), color('Moss Leather Stitch Pants', 6) },
        { color('Black & Red Leather Stitch Pants', 1), color('White Leather Stitch Pants', 2), color('Red Leather Stitch Pants', 4), color('Blue Leather Stitch Pants', 5) }),
    expanded('wide_designer', 118, nil, { 'designer', 'nightlife' },
        { color('Black Perseus Wide Pants', 0), color('Black P Wide Pants', 5), color('Black E Wide Pants', 6), color('White Broker Wide Pants', 7) },
        { color('Teal Perseus Wide Pants', 1), color('Blue Perseus Wide Pants', 2), color('Blue P Wide Pants', 3) },
        { color('White P Wide Pants', 4), color('Purple Lazerforce Wide Pants', 8) }),
    expanded('track', 128, nil, { 'sport' },
        { color('Cream Sports Track Pants', 0), color('Gray Heat Sports Track Pants', 1), color('White Heat Sports Track Pants', 6) },
        { color('Stone Sports Track Pants', 8), color('Blue Sports Track Pants', 9) },
        { color('Mustard Heat Sports Track Pants', 2), color('Purple Heat Sports Track Pants', 3), color('Orange Heat Sports Track Pants', 4), color('Pink Heat Sports Track Pants', 5), color('Cyan Heat Sports Track Pants', 7) }),
    expanded('large_cargo', 129, nil, { 'utility', 'street' },
        { color('Black Large Cargos', 1), color('Dark Gray Large Cargos', 3), color('Light Gray Large Cargos', 4), color('Ash Large Cargos', 6) },
        { color('Navy Large Cargos', 0), color('Khaki Large Cargos', 2), color('Stone Large Cargos', 5) },
        { color('Blue Large Cargos', 7) }),
    expanded('cuffed_sweats', 138, nil, { 'casual', 'street', 'sport' },
        { color('Black Cuffed Sweats', 1), color('Gray Cuffed Sweats', 2), color('Beige Cuffed Sweats', 3) },
        { color('Brown Cuffed Sweats', 0), color('Navy Cuffed Sweats', 4), color('Dark Nut Cuffed Sweats', 5), color('Dark Green Cuffed Sweats', 6) },
        { color('Red FB Cuffed Sweats', 7), color('Green FB Cuffed Sweats', 8) }),
    expanded('straight_chinos', 141, nil, { 'polished', 'casual', 'nightlife' },
        { color('Black Straight Chinos', 0), color('Gray Straight Chinos', 1), color('Ash Straight Chinos', 2), color('White Straight Chinos', 3) },
        { color('Beige Straight Chinos', 4), color('Navy Straight Chinos', 5), color('Dark Nut Straight Chinos', 6) },
        { color('Green SC Floral Straight Chinos', 7), color('Beige SC Floral Straight Chinos', 8) }),
    expanded('beach_shorts', 143, nil, { 'resort', 'sport' },
        { color('Black Beach', 0), color('Gray Beach', 1), color('Ash Beach', 2), color('Ice Beach', 3) },
        { color('Beige Beach', 4), color('Olive Beach', 5) },
        { color('Purple Swallow Tie-dye Beach', 6), color('Light VDG Beach', 7) }),
    expanded('jean_shorts', 145, nil, { 'resort', 'casual' },
        { color('White Jean Shorts', 0), color('Gray Jean Shorts', 1), color('Charcoal Jean Shorts', 2), color('Black Jean Shorts', 3) },
        { color('Indigo Jean Shorts', 4), color('Light Jean Shorts', 5), color('Stonewash Jean Shorts', 6) },
        { color('Standard Jean Shorts', 7), color('Classic Jean Shorts', 8) }),
    expanded('turnups', 151, nil, { 'casual', 'street', 'polished' },
        { color('Gray Turnups', 1), color('Charcoal Turnups', 2), color('Black Turnups', 3) },
        { color('Indigo Turnups', 4), color('Light Turnups', 5), color('Stonewash Turnups', 6) },
        { color('White Turnups', 0), color('Standard Turnups', 7), color('Classic Turnups', 8) }),
    expanded('laced_leather', 148, nil, { 'biker', 'nightlife' },
        { color('Black Laced Leather', 0), color('Dark Gray Laced Leather', 1), color('Light Gray Laced Leather', 2) },
        { color('Ox Blood Laced Leather', 4), color('Green Laced Leather', 6) },
        { color('White Laced Leather', 3), color('Scarlet Laced Leather', 5), color('Red Laced Leather', 7) }),
    expanded('snap_joggers', 173, nil, { 'sport', 'street' },
        { color('Black Snap Joggers', 0), color('Dark Gray Snap Joggers', 1), color('Gray Snap Joggers', 2) },
        { color('Beige Snap Joggers', 4), color('Chocolate Snap Joggers', 5), color('Burgundy Snap Joggers', 6) },
        { color('Hot Pink Snap Joggers', 7), color('Scarlet Snap Joggers', 8) }),
}) do AppearanceCatalog.male.bottoms[#AppearanceCatalog.male.bottoms + 1] = entry end
for _, entry in ipairs({
    expanded('knit', 99, nil, { 'casual', 'street', 'sport', 'designer' },
        { color('Ice Knit Sneakers', 0), color('White Knit Sneakers', 1), color('Black Knit Sneakers', 3), color('Smoky Knit Sneakers', 5) },
        { color('Aqua Sole Knit Sneakers', 2), color('Cream Knit Sneakers', 4) },
        { color('Lime Highlight Knit Sneakers', 6), color('Pink Vibrant Knit Sneakers', 7), color('Lilac Knit Sneakers', 8), color('Red Highlight Knit Sneakers', 9) }),
    expanded('road', 103, nil, { 'biker' },
        { color('Black Road Boots', 0), color('Ash Road Boots', 4), color('Dark Gray Road Boots', 5) },
        { color('Ox Blood Road Boots', 1), color('Chestnut Road Boots', 3), color('Tan Road Boots', 6), color('Dark Green Road Boots', 7) },
        { color('Red Road Boots', 2), color('Gray Road Boots', 8) }),
    expanded('smart_oxford', 105, nil, { 'polished', 'nightlife' },
        { color('Black Smart Oxfords', 1), color('Gray Smart Oxfords', 2), color('Ice Smart Oxfords', 3) },
        { color('Walnut Smart Oxfords', 0), color('Dark Nut Smart Oxfords', 4), color('Chocolate Smart Oxfords', 5) },
        { color('Chestnut Smart Oxfords', 6), color('Beige Smart Oxfords', 7) }),
    expanded('buckled', 107, nil, { 'polished', 'resort', 'nightlife', 'designer' },
        { color('Black Buckled Loafers', 0), color('Gray Buckled Loafers', 1), color('Beige Buckled Loafers', 6) },
        { color('Chocolate Buckled Loafers', 3), color('Ox Blood Buckled Loafers', 4), color('Dark Tan Buckled Loafers', 5) },
        { color('Lilac Buckled Loafers', 2), color('Blue Buckled Loafers', 7) }),
    expanded('pool_sliders', 109, nil, { 'resort' },
        { color('Black Bigness Pool Sliders', 0), color('Black Blagueurs Pool Sliders', 3), color('White Blagueurs Pool Sliders', 4), color('Gray Cimicino Pool Sliders', 6) },
        { color('Camo Bigness Pool Sliders', 2) },
        { color('Purple Bigness Pool Sliders', 1), color('Pink Blagueurs Pool Sliders', 5), color('Rouge Cimicino Pool Sliders', 7) }),
    expanded('logger', 112, nil, { 'utility', 'biker' },
        { color('Black Loggers', 0), color('Gray Loggers', 1), color('Light Gray Loggers', 2), color('Ice Loggers', 3) },
        { color('Chocolate Loggers', 4), color('Russet Loggers', 5), color('Green Loggers', 6) },
        { color('Red Loggers', 7), color('Orange Tan Loggers', 8) }),
    expanded('low_canvas', 116, nil, { 'casual', 'street', 'resort' },
        { color('Black Low Canvas', 0), color('Dark Gray Low Canvas', 1), color('Gray Low Canvas', 2), color('Ice Low Canvas', 3) },
        { color('Beige Low Canvas', 4), color('Chocolate Low Canvas', 5), color('Burgundy Low Canvas', 6) },
        { color('Hot Pink Low Canvas', 7), color('Scarlet Low Canvas', 8) }),
    expanded('designer_lace', 128, nil, { 'designer', 'street', 'sport' },
        { color('Black Designer Lace-Up', 0), color('Dark Gray Designer Lace-Up', 1), color('Gray Designer Lace-Up', 2), color('Ice Designer Lace-Up', 3) },
        { color('Beige Designer Lace-Up', 4), color('Chocolate Designer Lace-Up', 5), color('Burgundy Designer Lace-Up', 6) },
        { color('Hot Pink Designer Lace-Up', 7), color('Scarlet Designer Lace-Up', 8), color('Orange Designer Lace-Up', 9) }),
}) do AppearanceCatalog.male.shoes[#AppearanceCatalog.male.shoes + 1] = entry end
for _, entry in ipairs({
    expanded('office', 367, 3, { 'polished', 'nightlife' },
        { color('White Office', 0), color('Black Office', 3), color('Stone Office', 6) },
        { color('Navy Office', 2), color('Beige Office', 4), color('Ivory Office', 5) },
        { color('Berry Office', 7), color('Ash Office', 8), color('Gray Office', 9) }),
    expanded('office_open', 366, 3, { 'polished', 'nightlife' },
        { color('White Office Unbuttoned', 0), color('Black Office Unbuttoned', 3), color('Stone Office Unbuttoned', 6) },
        { color('Navy Office Unbuttoned', 2), color('Beige Office Unbuttoned', 4), color('Ivory Office Unbuttoned', 5) },
        { color('Berry Office Unbuttoned', 7), color('Ash Office Unbuttoned', 8), color('Gray Office Unbuttoned', 9) }),
    expanded('brand_polo', 368, 14, { 'polished', 'casual', 'resort', 'designer' },
        { color('White B Polo Shirt', 1), color('White FB Polo Shirt', 3), color('White Bigness Polo Shirt', 5) },
        { color('Purple B Polo Shirt', 0), color('Purple FB Polo Shirt', 2), color('Purple Bigness Polo Shirt', 4) },
        { color('Purple B Polo Shirt', 0), color('Purple FB Polo Shirt', 2), color('Purple Bigness Polo Shirt', 4) }),
    expanded('revere', 429, 0, { 'polished', 'resort', 'nightlife' },
        { color('Black Revere Collar', 0), color('Dark Gray Revere Collar', 1), color('Ice Revere Collar', 3) },
        { color('Beige Revere Collar', 4), color('Chocolate Revere Collar', 5), color('Burgundy Revere Collar', 6) },
        { color('Hot Pink Revere Collar', 7), color('Scarlet Revere Collar', 8), color('Orange Revere Collar', 9) }),
    expanded('cardigan', 451, 5, { 'polished', 'casual', 'nightlife' },
        { color('Black Cardigan', 0), color('Dark Gray Cardigan', 1), color('Ice Cardigan', 3) },
        { color('Beige Cardigan', 4), color('Chocolate Cardigan', 5), color('Burgundy Cardigan', 6) },
        { color('Hot Pink Cardigan', 7), color('Scarlet Cardigan', 8), color('Tangerine Cardigan', 9) }),
    expanded('designer_cardigan', 474, 5, { 'polished', 'designer', 'nightlife' },
        { color('Black Blagueurs Cardigan', 0), color('White Blagueurs Cardigan', 3) },
        { color('Blue Blagueurs Cardigan', 1), color('Blue DS Panthers Cardigan', 4), color('Blue DS Tiger Cardigan', 6) },
        { color('Red Blagueurs Cardigan', 2), color('Red DS Panthers Cardigan', 5), color('Red DS Tiger Cardigan', 7) }),
    expanded('chore', 409, 3, { 'polished', 'casual', 'utility' },
        { color('Ash Chore', 1), color('Gray Chore', 2), color('Black Chore', 3) },
        { color('Beige Chore', 4), color('Navy Chore', 5), color('Olive Chore', 6) },
        { color('Ice Chore', 0), color('Pink Chore', 7) }),
    expanded('double_shirt', 356, 3, { 'casual', 'street', 'utility' },
        { color('Black Double Shirt', 0), color('Gray Double Shirt', 1), color('White Double Shirt', 2) },
        { color('Navy Double Shirt', 3), color('Orange Double Shirt', 4), color('Pink Double Shirt', 5) },
        { color('Green Double Shirt', 6), color('Red Double Shirt', 7) }),
    expanded('pullover', 407, 3, { 'casual', 'street', 'sport' },
        { color('Black Pullover Hoodie', 0), color('Dark Gray Pullover Hoodie', 1), color('Light Gray Pullover Hoodie', 2), color('White Pullover Hoodie', 3) },
        { color('Beige Pullover Hoodie', 4), color('Brown Pullover Hoodie', 5), color('Maroon Pullover Hoodie', 6) },
        { color('Hot Pink Pullover Hoodie', 7), color('Red Pullover Hoodie', 8), color('Orange Pullover Hoodie', 9) }),
    expanded('brand_hoodie', 271, 3, { 'street', 'designer' },
        { color('Gray Sports Blagueurs Hoodie', 0), color('Black Sports Blagueurs Hoodie', 1), color('White College Blagueurs Hoodie', 2), color('Gray College Blagueurs Hoodie', 3) },
        { color('Spotted Dark GÃ¼ffy Hoodie', 6), color('Blue Leaves GÃ¼ffy Hoodie', 8) },
        { color('Graffiti Black GÃ¼ffy Hoodie', 4), color('Sprayed Green GÃ¼ffy Hoodie', 5), color('Neon Leaves GÃ¼ffy Hoodie', 7) }),
    expanded('casino_bomber', 309, 3, { 'street', 'designer', 'nightlife' },
        { color('Black Bigness Bomber', 0), color('White Bigness Bomber', 1), color('Black Broker Coin Bomber', 2), color('White Broker Coin Bomber', 3) },
        { color('Teal Broker Coin Bomber', 6), color('Black SC Broker Bomber', 7) },
        { color('Red Broker Coin Bomber', 4), color('Purple Broker Coin Bomber', 5) }),
    expanded('zipped_bigness', 362, 3, { 'casual', 'street', 'designer' },
        { color('Black Bigness Bomber Zipped', 0), color('Black 22 Bomber Zipped', 2), color('Black Detail Bomber Zipped', 3) },
        { color('Black Bigness Bomber Zipped', 0), color('Black Trickster Bomber Zipped', 5) },
        { color('Yellow Bigness Bomber Zipped', 1), color('Yellow Detail Bomber Zipped', 4), color('Yellow Trickster Bomber Zipped', 6) }),
    expanded('broker_puffer', 320, 5, { 'street', 'designer' },
        { color('Black Broker Puffer', 1), color('Black GÃ¼ffy Spray Puffer', 6) },
        { color('Maroon Broker Puffer', 0), color('Teal Broker Puffer', 2), color('Green FB Puffer', 3) },
        { color('Purple FB Puffer', 4), color('Yellow FB Puffer', 5), color('Turquoise GÃ¼ffy Spray Puffer', 7) }),
    expanded('track_top', 347, 3, { 'sport', 'casual' },
        { color('Cream Sports Track Top', 0), color('Gray Heat Sports Track Top', 1), color('White Heat Sports Track Top', 6) },
        { color('Orange Prolaps Sports Track Top', 8), color('Yellow Prolaps Sports Track Top', 9) },
        { color('Mustard Heat Sports Track Top', 2), color('Purple Heat Sports Track Top', 3), color('Orange Heat Sports Track Top', 4), color('Pink Heat Sports Track Top', 5), color('Cyan Heat Sports Track Top', 7) }),
    expanded('racing', 390, 3, { 'biker', 'street' },
        { color('Black Bravado Modern Racing', 0), color('Dark Dinka Modern Racing', 4) },
        { color('Blue Bravado Modern Racing', 1), color('Blue Dinka Modern Racing', 7) },
        { color('Fade Broker Modern Racing', 2), color('Yellow Vapid Modern Racing', 3), color('Light Dinka Modern Racing', 5), color('Red Dinka Modern Racing', 6) }),
    expanded('retro_racing', 396, 1, { 'biker', 'street' },
        { color('White Globe Oil Retro Racing', 1), color('Black Crowex Retro Racing', 2) },
        { color('Green Crowex Retro Racing', 3), color('Blue Atomic Retro Racing', 5), color('Blue Redwood Retro Racing', 6) },
        { color('Red Globe Oil Retro Racing', 0), color('Yellow Atomic Retro Racing', 4), color('Red Redwood Retro Racing', 7) }),
    expanded('leather_bomber', 397, 3, { 'biker', 'casual', 'nightlife' },
        { color('Mono Leather Bomber', 0) },
        { color('Dark Tan Leather Bomber', 2), color('Dark Green Leather Bomber', 3), color('Dark Nut Leather Bomber', 4), color('Navy Blue Leather Bomber', 6) },
        { color('Ox Blood Leather Bomber', 1), color('Orange Tan Leather Bomber', 5), color('Red Leather Bomber', 7) }),
    expanded('light_biker', 427, 3, { 'biker', 'nightlife' },
        { color('Black Light Biker', 0), color('Gray Light Biker', 1), color('Ash Light Biker', 2), color('Ice Light Biker', 3) },
        { color('Ox Blood Light Biker', 4), color('Dark Green Light Biker', 6) },
        { color('Scarlet Light Biker', 5), color('Red Light Biker', 7) }),
    expanded('field_blouson', 252, 5, { 'utility' },
        { color('Khaki Tactical Blouson', 0), color('Green Tactical Blouson', 1) },
        { color('Khaki Tactical Blouson', 0), color('Green Tactical Blouson', 1) },
        { color('Grayscale Tactical Blouson', 2), color('Dazzle Tactical Blouson', 3) }),
    expanded('waterproof', 307, 3, { 'utility', 'street' },
        { color('Black Bigness Waterproof', 0) },
        { color('Black Bigness Waterproof', 0) },
        { color('Cyan Bigness Waterproof', 1), color('Magenta Bigness Waterproof', 2), color('Red Bigness Waterproof', 3) }),
    expanded('botanical', 372, 9, { 'resort' },
        { color('Black Botanical Shortsleeve', 1), color('Black Blossom Shortsleeve', 3) },
        { color('Blue Blossom Shortsleeve', 2), color('Blue Blooming Shortsleeve', 4), color('Green Floral Shortsleeve', 6) },
        { color('Red Botanical Shortsleeve', 0), color('Orange Blooming Shortsleeve', 5), color('Cream Floral Shortsleeve', 7) }),
    expanded('palms', 430, 0, { 'resort', 'nightlife' },
        { color('Charcoal Floral Revere Collar', 2), color('Charcoal Palms Revere Collar', 4) },
        { color('Green Palms Revere Collar', 0), color('Cool Sunset Revere Collar', 6) },
        { color('Blush Palms Revere Collar', 1), color('Red Floral Revere Collar', 3), color('Pink Palms Revere Collar', 5), color('Warm Sunset Revere Collar', 7) }),
}) do AppearanceCatalog.female.tops[#AppearanceCatalog.female.tops + 1] = entry end
for _, entry in ipairs({
    expanded('chain', 109, nil, { 'street', 'biker' },
        { color('Black Chain Pants', 0), color('Gray Chain Pants', 1), color('White Chain Pants', 2) },
        { color('Brown Chain Pants', 3), color('Tan Chain Pants', 4), color('Beige Chain Pants', 5) },
        { color('Gray Camo Chain Pants', 6), color('Green Camo Chain Pants', 7) }),
    expanded('leather_stitch', 112, nil, { 'biker', 'nightlife' },
        { color('Black Leather Stitch Pants', 0), color('Gray Leather Stitch Pants', 7) },
        { color('Dark Red Leather Stitch Pants', 3), color('Moss Leather Stitch Pants', 6) },
        { color('Black & Red Leather Stitch Pants', 1), color('White Leather Stitch Pants', 2), color('Red Leather Stitch Pants', 4), color('Blue Leather Stitch Pants', 5) }),
    expanded('wide_designer', 124, nil, { 'designer', 'nightlife' },
        { color('Black Perseus Wide Pants', 0), color('Black P Wide Pants', 5), color('Black E Wide Pants', 6), color('White Broker Wide Pants', 7) },
        { color('Teal Perseus Wide Pants', 1), color('Blue Perseus Wide Pants', 2), color('Blue P Wide Pants', 3) },
        { color('White P Wide Pants', 4), color('Purple Lazerforce Wide Pants', 8) }),
    expanded('track', 134, nil, { 'sport' },
        { color('Cream Sports Track Pants', 0), color('Gray Heat Sports Track Pants', 1), color('White Heat Sports Track Pants', 6) },
        { color('Stone Sports Track Pants', 8), color('Blue Sports Track Pants', 9) },
        { color('Mustard Heat Sports Track Pants', 2), color('Purple Heat Sports Track Pants', 3), color('Orange Heat Sports Track Pants', 4), color('Pink Heat Sports Track Pants', 5), color('Cyan Heat Sports Track Pants', 7) }),
    expanded('large_cargo', 135, nil, { 'utility', 'street' },
        { color('Black Large Cargos', 1), color('Dark Gray Large Cargos', 3), color('Light Gray Large Cargos', 4), color('Ash Large Cargos', 6) },
        { color('Navy Large Cargos', 0), color('Khaki Large Cargos', 2), color('Stone Large Cargos', 5) },
        { color('Blue Large Cargos', 7) }),
    expanded('cuffed_sweats', 145, nil, { 'casual', 'street', 'sport' },
        { color('Black Cuffed Sweats', 1), color('Gray Cuffed Sweats', 2), color('Beige Cuffed Sweats', 3) },
        { color('Brown Cuffed Sweats', 0), color('Navy Cuffed Sweats', 4), color('Dark Nut Cuffed Sweats', 5), color('Dark Green Cuffed Sweats', 6) },
        { color('Red FB Cuffed Sweats', 7), color('Green FB Cuffed Sweats', 8) }),
    expanded('straight_chinos', 148, nil, { 'polished', 'casual', 'nightlife' },
        { color('Black Straight Chinos', 0), color('Gray Straight Chinos', 1), color('Ash Straight Chinos', 2), color('White Straight Chinos', 3) },
        { color('Beige Straight Chinos', 4), color('Navy Straight Chinos', 5), color('Dark Nut Straight Chinos', 6) },
        { color('Green SC Floral Straight Chinos', 7), color('Beige SC Floral Straight Chinos', 8) }),
    expanded('beach_shorts', 150, nil, { 'resort', 'sport' },
        { color('Black Beach', 0), color('Gray Beach', 1), color('Ash Beach', 2), color('Ice Beach', 3) },
        { color('Beige Beach', 4), color('Olive Beach', 5) },
        { color('Purple Swallow Tie-dye Beach', 6), color('Light VDG Beach', 7) }),
    expanded('jean_shorts', 154, nil, { 'resort', 'casual' },
        { color('White Jean Shorts', 0), color('Gray Jean Shorts', 1), color('Charcoal Jean Shorts', 2), color('Black Jean Shorts', 3) },
        { color('Indigo Jean Shorts', 4), color('Light Jean Shorts', 5), color('Stonewash Jean Shorts', 6) },
        { color('Standard Jean Shorts', 7), color('Classic Jean Shorts', 8) }),
    expanded('turnups', 160, nil, { 'casual', 'street', 'polished' },
        { color('Gray Turnups', 1), color('Charcoal Turnups', 2), color('Black Turnups', 3) },
        { color('Indigo Turnups', 4), color('Light Turnups', 5), color('Stonewash Turnups', 6) },
        { color('White Turnups', 0), color('Standard Turnups', 7), color('Classic Turnups', 8) }),
    expanded('laced_leather', 156, nil, { 'biker', 'nightlife' },
        { color('Black Laced Leather', 0), color('Dark Gray Laced Leather', 1), color('Light Gray Laced Leather', 2) },
        { color('Ox Blood Laced Leather', 4), color('Green Laced Leather', 6) },
        { color('White Laced Leather', 3), color('Scarlet Laced Leather', 5), color('Red Laced Leather', 7) }),
    expanded('snap_joggers', 185, nil, { 'sport', 'street' },
        { color('Black Snap Joggers', 0), color('Dark Gray Snap Joggers', 1), color('Gray Snap Joggers', 2) },
        { color('Beige Snap Joggers', 4), color('Chocolate Snap Joggers', 5), color('Burgundy Snap Joggers', 6) },
        { color('Hot Pink Snap Joggers', 7), color('Scarlet Snap Joggers', 8) }),
}) do AppearanceCatalog.female.bottoms[#AppearanceCatalog.female.bottoms + 1] = entry end
for _, entry in ipairs({
    expanded('knit', 103, nil, { 'casual', 'street', 'sport', 'designer' },
        { color('Ice Knit Sneakers', 0), color('White Knit Sneakers', 1), color('Black Knit Sneakers', 3), color('Smoky Knit Sneakers', 5) },
        { color('Aqua Sole Knit Sneakers', 2), color('Cream Knit Sneakers', 4) },
        { color('Lime Highlight Knit Sneakers', 6), color('Pink Vibrant Knit Sneakers', 7), color('Lilac Knit Sneakers', 8), color('Red Highlight Knit Sneakers', 9) }),
    expanded('road', 107, nil, { 'biker' },
        { color('Black Road Boots', 0), color('Ash Road Boots', 4), color('Dark Gray Road Boots', 5) },
        { color('Ox Blood Road Boots', 1), color('Chestnut Road Boots', 3), color('Tan Road Boots', 6), color('Dark Green Road Boots', 7) },
        { color('Red Road Boots', 2), color('Gray Road Boots', 8) }),
    expanded('smart_oxford', 109, nil, { 'polished', 'nightlife' },
        { color('Black Smart Oxfords', 1), color('Gray Smart Oxfords', 2), color('Ice Smart Oxfords', 3) },
        { color('Walnut Smart Oxfords', 0), color('Dark Nut Smart Oxfords', 4), color('Chocolate Smart Oxfords', 5) },
        { color('Chestnut Smart Oxfords', 6), color('Beige Smart Oxfords', 7) }),
    expanded('buckled', 111, nil, { 'polished', 'resort', 'nightlife', 'designer' },
        { color('Black Buckled Loafers', 0), color('Gray Buckled Loafers', 1), color('Beige Buckled Loafers', 6) },
        { color('Chocolate Buckled Loafers', 3), color('Ox Blood Buckled Loafers', 4), color('Dark Tan Buckled Loafers', 5) },
        { color('Lilac Buckled Loafers', 2), color('Blue Buckled Loafers', 7) }),
    expanded('pool_sliders', 113, nil, { 'resort' },
        { color('Black Bigness Pool Sliders', 0), color('Black Blagueurs Pool Sliders', 3), color('White Blagueurs Pool Sliders', 4), color('Gray Cimicino Pool Sliders', 6) },
        { color('Camo Bigness Pool Sliders', 2) },
        { color('Purple Bigness Pool Sliders', 1), color('Pink Blagueurs Pool Sliders', 5), color('Rouge Cimicino Pool Sliders', 7) }),
    expanded('logger', 116, nil, { 'utility', 'biker' },
        { color('Black Loggers', 0), color('Gray Loggers', 1), color('Light Gray Loggers', 2), color('Ice Loggers', 3) },
        { color('Chocolate Loggers', 4), color('Russet Loggers', 5), color('Green Loggers', 6) },
        { color('Red Loggers', 7), color('Orange Tan Loggers', 8) }),
    expanded('low_canvas', 120, nil, { 'casual', 'street', 'resort' },
        { color('Black Low Canvas', 0), color('Dark Gray Low Canvas', 1), color('Gray Low Canvas', 2), color('Ice Low Canvas', 3) },
        { color('Beige Low Canvas', 4), color('Chocolate Low Canvas', 5), color('Burgundy Low Canvas', 6) },
        { color('Hot Pink Low Canvas', 7), color('Scarlet Low Canvas', 8) }),
    expanded('designer_lace', 132, nil, { 'designer', 'street', 'sport' },
        { color('Black Designer Lace-Up', 0), color('Dark Gray Designer Lace-Up', 1), color('Gray Designer Lace-Up', 2), color('Ice Designer Lace-Up', 3) },
        { color('Beige Designer Lace-Up', 4), color('Chocolate Designer Lace-Up', 5), color('Burgundy Designer Lace-Up', 6) },
        { color('Hot Pink Designer Lace-Up', 7), color('Scarlet Designer Lace-Up', 8), color('Orange Designer Lace-Up', 9) }),
}) do AppearanceCatalog.female.shoes[#AppearanceCatalog.female.shoes + 1] = entry end
