"""Package Colbss/FiveM-ClothingData photos for the curated catalog.

Not a runtime dependency. Re-run when expanding shared/appearance_catalog.lua.
Images depict the catalog drawable, usually texture zero, not a live preview.
"""
from pathlib import Path
from urllib.request import Request, urlopen
from concurrent.futures import ThreadPoolExecutor
import re
import json

ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT / 'ui' / 'wardrobe'
DEST.mkdir(exist_ok=True)
catalog = (ROOT / 'shared/appearance_catalog.lua').read_text(encoding='utf-8')
sources = []
COMMIT = '6178655616ea88e3e2bf191b32bc4878b9c3b5eb'
BASE = f'https://raw.githubusercontent.com/Colbss/FiveM-ClothingData/{COMMIT}/'

def read(url):
    return urlopen(Request(url, headers={'User-Agent': 'CortexWardrobeCatalog/1.0'}), timeout=25).read()

tree = json.loads(read(f'https://api.github.com/repos/Colbss/FiveM-ClothingData/git/trees/{COMMIT}?recursive=1'))
paths = {entry['path'] for entry in tree['tree']}
index = {}
for gender, letter in [('male', 'M'), ('female', 'F')]:
    definitions = json.loads(read(BASE + gender + '_drawables.json'))
    mapping = {}
    for collection, components in definitions.items():
        for key, component in [('JBIB', 11), ('LOWR', 4), ('FEET', 6), ('UPPR', 3), ('ACCS', 8)]:
            for local_id, entry in components.get(key, {}).items():
                mapping[(component, entry['globalId'])] = (collection, int(local_id))
    index[gender] = mapping
    section = catalog.split('AppearanceCatalog.' + gender + ' = {')[1].split('AppearanceCatalog.')[0]
    for category, component, page in [('tops', 11, 'Tops'), ('bottoms', 4, 'Legs'), ('shoes', 6, 'Shoes')]:
        part = section.split('    ' + category + ' = {')[1].split('\n    },')[0]
        ids = set(map(int, re.findall(r"(?:top|garment)\('[^']+', (\d+)", part)))
        # Expansion blocks append to the same runtime catalog. Include their
        # photographs when the upstream library actually has them.
        for block, body, kind in re.findall(
                r'for _, entry in ipairs\(\{(.*?)\}\) do AppearanceCatalog\.(male|female)\.(tops|bottoms|shoes)',
                catalog, re.S):
            if body == gender and kind == category:
                ids.update(map(int, re.findall(r"expanded\('[^']+', (\d+)", block)))
        for drawable in sorted(ids):
            collection, local_id = mapping[(component, drawable)]
            path = f'images/mp_{gender[0]}_freemode_01/{collection}/D_{component}_{local_id}_0.webp'
            if path not in paths:
                continue
            sources.append({'file': f'{gender}-{component}-{drawable}.webp', 'source': BASE + path})

def download(entry):
    path = DEST / entry['file']
    if not path.exists():
        path.write_bytes(read(entry['source']))
    return entry

with ThreadPoolExecutor(max_workers=4) as executor:
    results = list(executor.map(download, sources))
(DEST / 'sources.json').write_text(json.dumps(results, indent=2) + '\n')
lines = ['-- Generated by tools/fetch-wardrobe-thumbnails.py; source build 3407, commit ' + COMMIT,
         '-- Collection identity is checked against the running ped before curated items are used.', 'AppearanceIndex = {']
for gender, mapping in index.items():
    lines.append('    ' + gender + ' = {')
    for component in [3, 4, 6, 8, 11]:
        lines.append(f'        [{component}] = {{')
        for (comp, drawable), (collection, local_id) in sorted(mapping.items()):
            if comp == component:
                photo = any(e['file'] == f'{gender}-{component}-{drawable}.webp' for e in results)
                lines.append(f'            [{drawable}] = {{ collection = {json.dumps(collection)}, drawable = {local_id}, photo = {str(photo).lower()} }},')
        lines.append('        },')
    lines.append('    },')
lines.append('}')
(ROOT / 'shared' / 'appearance_index.lua').write_text('\n'.join(lines) + '\n')
print(f'Packaged {len(results)} catalog reference photographs.')
